language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  sauce_connect: true
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: YycavrvP1kxU3/ip55wfi3nIA0b9C7IR7Uv5iPA99ZyfiyIqzojRkK8j24eLjLUHF9erzSYaMBQCAmRAKoFeUXG/wAc96L2z9UUZsThpIsVtpNXkjSKnz7z/RQOMB67fIJmGUGs6WpJqkXb1nhl/FOQ7HYq5piQkO9T36xZuMJcM1gdEZDjzkldNaNg/oaTEe9kmNPAtUWdrQFjzCjaK8ivPbDvRhbQlptxat/8PVmiejlenVZkLFUNdRDQbC5mJrICeAtw8wsF6EelVY5iG/l+fkHP1Oet/e5MTyvNvwNOaKDcwdrR6ENNUWksaeaFNSFQuECBh5UUtjDzkABKHAK+nflMHoHnjTdrlOsvWm+oMolux7LOPaOgxzqgukwopMV87MBEpQIy5fP7awc9F7qrQJ1iNDsWuYvU1hGunAWdnQ8auVLEpq/Rxtj+qGgp7xap1QfDCq/2XF0YU047akAv5TGKXGFW0wImbHSQ7w9KN6U3zJvsRrrdW5o7sKb30iDLSjB0vvvQrBkTfX7veGyHUO50335MeHEiEtB662khpHUvYXle0eITbU8RgQpVVhCAPzg2bwahwPzS3X6Nb9/jtppUE6Eoz1VGJe3SX9zXoHAumO8ENFwTPnI/0/8RJl3C0vRwrg5JtN7ZMw9TXopS8X2eaRPZyn/U1mvjk+ZA=
  - secure: fOakyvLOQlz3Ayeh4jkTRjkBbYq/vB+AxcNSjUp2lOrz48X/KH0QquLzOxPLnZa7aGZtFqN02DUTJLcpPj5fl0tkhqgK6t4k7DzWvqi4Cq0usKsSKOKj0WYHHqqYuNIUX56WDXa6CkkXhv52zoSrrqf4P1/T5qt6ebs3lIXGbT3wM6qHMEZkTBxJydtrkqG+vjKclbLvcXvR3VsPJZ3ticLGfEHbSIHG7m52zTQuRFrGuoXTOYM1rb0NLkZ5oYSLxXiYZzoU10FjY08y72PxfzOJNSrvYZKC9+AQmxhZw/KGhLyk/4i9M/j+tAB1xSkYEsYUrsGcOlnlpJ/KYvMPtEmR0KKK10F3q6AiumaSwF6uF0/cYk7bfcDO/pWWX/O5JrYG74Oj2KiiVUZuOY13H4MuEelhv2YYWXln7CzVPEEueI5lJxrB3EEA3EiI4WolWF5PtHGnoljZBvEQ6sCdojPYwICPqVFIfLQyONRQcktjvHdy64i2qo1IkIaRyoo5Ev+7lyHngdb/9OIb9Cvmr7CfDrul5vQ20qSadb6ydSkISLB5J1Ljm9k35oROljPrQ6vcMSBZvdJmwkUdqhB+Yo65Fp/ffosl/WNAVWF2CLEa7aXK3Xm9clMEXvymm6oUxI0W1doDI+bCAAW8EDWkLNloRZOfL4BCO/dxF1bnmsM=
